= Hardware specifications

Where did your run your tests? A laptop, or goldengate?

Goldengate

What are the performance specifications of the machine: number and speed of
processors, size of RAM? (use `lscpu` and `free -m`)

CPU speed: 3.40 GHz

CPU number: 64

= Allocations

In `simple.c`, where does the increase in 1040 bytes come from?
Why is the value 1040 bytes?

Printf allocated 1024 bytes along with 16 bytes for the chunk header.
(Since the version of malloc in myalloc_c has a chunk header implementation (with 16 bytes))
This results in the 1040 byte increase.

How many bytes does `mylloc_list.c` allocate when the program ends? Explain why
this amount makes sense.

Bytes allocated 1156 (0x484).

Each allocation is allocating one struct chunk and one printf.
From simple.c, know that printf allocates 1024 bytes while the
struct chunk has a size of 16 (int size = 8 and pointer next = 8).

There is also an additional 100 bytes (the size of the malloc block). This malloc also
creates an additional chunk header (so +16 bytes).

As such, this amount would be: 1024 + 16 + 100 + 16 = 1156 bytes.


= Fragmentation

Fragmentation is when there are "chunks of free heap space interspersed with chunks of allocated heap space"
(quoting text book).
Essentially, fragmentation eaves free chunks between allocated chunks.
These chunks are created by calls of malloc/free.

I'm going to explain internal fragmentation via an example:
Say 100 bytes is allocated then free'd. Then there would be
100 bytes in the flist. If the next allocation is 80 bytes, then by our current logic,
the 100 bytes chunk in flist would be the space where the 80 bytes were allocated.
If the next set of bytes to be allocated is 20, it would not take the 20 bytes of unused space
from the last allocation but rather create a new chunk of 20 bytes (or get another chunk in flist).
These unused spaces that are created during the allocation of chunks from flist is internal fragmentation.

External fragmentation is when (to prevent internal fragmentation) the chunks are divided into smaller pieces.
However, these pieces are too small to accommodate some larger allocations of memory.
In other words, there would be plenty of free space (but in smaller chunks) but the memory cannot be allocated
from these chunks. As such, (to solve this) the chunks need to be combined to create a larger chunk that can hold the memory allocated.

= Output

benchmark2:

The initial top of the heap is 0x7f315c7a8000.
Total blocks: 161 Free: 103 Used: 58
Internal unused: total: 178682 average: 3080.0 smallest: 511 largest: 3979
External unused: total: 144345 average: 1401.0 smallest: 10 largest: 3984
0
The current top of the heap is 0x7f315c7fe527.
Increased by 345 (0x159) Kbyte
Total blocks: 167 Free: 113 Used: 54
Internal unused: total: 159454 average: 2952.0 smallest: 107 largest: 3991
External unused: total: 177549 average: 1571.0 smallest: 10 largest: 3984
1
The current top of the heap is 0x7f315c804327.
Increased by 368 (0x170) Kbyte
Total blocks: 169 Free: 117 Used: 52
Internal unused: total: 157088 average: 3020.0 smallest: 129 largest: 3977
External unused: total: 189341 average: 1618.0 smallest: 10 largest: 3997
2
The current top of the heap is 0x7f315c806282.
Increased by 376 (0x178) Kbyte
Total blocks: 172 Free: 120 Used: 52
Internal unused: total: 160672 average: 3089.0 smallest: 146 largest: 3989
External unused: total: 201235 average: 1676.0 smallest: 10 largest: 3998
3
The current top of the heap is 0x7f315c809188.
Increased by 388 (0x184) Kbyte
Total blocks: 175 Free: 125 Used: 50
Internal unused: total: 145974 average: 2919.0 smallest: 6 largest: 3984
External unused: total: 222205 average: 1777.0 smallest: 10 largest: 3999
4
The current top of the heap is 0x7f315c80c095.
Increased by 400 (0x190) Kbyte
Total blocks: 176 Free: 116 Used: 60
Internal unused: total: 191611 average: 3193.0 smallest: 984 largest: 3986
External unused: total: 189140 average: 1630.0 smallest: 10 largest: 3999
5
The current top of the heap is 0x7f315c80d045.
Increased by 404 (0x194) Kbyte
Total blocks: 176 Free: 128 Used: 48
Internal unused: total: 153391 average: 3195.0 smallest: 381 largest: 3991
External unused: total: 227231 average: 1775.0 smallest: 10 largest: 4000
6
The current top of the heap is 0x7f315c80d045.
Increased by 404 (0x194) Kbyte
Total blocks: 177 Free: 125 Used: 52
Internal unused: total: 154837 average: 2977.0 smallest: 138 largest: 3989
External unused: total: 219943 average: 1759.0 smallest: 10 largest: 3999
7
The current top of the heap is 0x7f315c80dff5.
Increased by 407 (0x197) Kbyte
Total blocks: 178 Free: 118 Used: 60
Internal unused: total: 193404 average: 3223.0 smallest: 401 largest: 3990
External unused: total: 193697 average: 1641.0 smallest: 10 largest: 4000
8
The current top of the heap is 0x7f315c80efa5.
Increased by 411 (0x19b) Kbyte
Total blocks: 178 Free: 130 Used: 48
Internal unused: total: 150237 average: 3129.0 smallest: 636 largest: 3987
External unused: total: 237661 average: 1828.0 smallest: 10 largest: 4000
9
The current top of the heap is 0x7f315c80efa5.
Increased by 411 (0x19b) Kbyte
